### ISSUE TITLE
Assigned Task

### ISSUE THREAD

**Issue by scortier** [scortier/NITS-Result-Portal#41]
**DEADLINE - 4 Jan 12pm**

**Table Layout and Responsiveness(Student Section)**(Assigned to @Saurav1905 and @Jitulteron7  )

- [x] Enlarge the size feasible for desktop view and curve the edges and for the mobile view - shift it to the centre of the screen.
- [x] Dim Shadow of the table on the background
For the user/settings
- [x] create space for the navbar, shift the profile pic and content downward.

**For Admin**
- [x] Change layout feasible for a desktop view like curve the edges, style the button,space-evenly. (@reverope )
- [x] Create a responsive table with same design as of the latest table layout in desktop (@aditya2712 )

- [x] Make a bottom one-line footer to write copyright claim and add in each page of the site (@reeyah ).

- [x] Add the feature to change profile picture (@gauravdas014 )

- [x] 1.Upload excel feature not working properly,(@KaviiSuri and @Debojyoti1915001 )
- [x] 2. check if admin upload the wrong format must show the error message (@KaviiSuri and @Debojyoti1915001 )

**Comment by aditya2712** [comment]
Bhaiya this issue is resolved please close this issue, the footer is also made.
